---
name: |
  Gustavo Diaz \
  Northwestern University
sender: "Gustavo Diaz, Northwestern Political Science, Scott Hall ste 224, 601 University Place, Evanston IL 60208"
subject: "Faculty Position, Department of Political Science"
format:
  letter-typst: default
---

```{r setup, include=F}
jobtitle = "call for tenure-track faculty in Comparative Politics/International Relations"
research = "the challenges to accountability, representation, and governance in the Global South"
place = "Sogang"
discipline = "political science"
subfield = "comparative politics and quantitative methods"
courses = "the required research methods sequence at all levels. I am also eager to develop new courses on comparative politics, politics of the Global South, Latin American Politics, and evidence-informed policy-making"
source = "website"
```


```{=typst}
#set text(
  size: 11pt
)
```



Dear Members of the Search Committee, 

I write to express my interest in your `r jobtitle`. I am an Assistant Professor of Instruction in the Department of Political Science at Northwestern University. My research centers on `r subfield`. My work is published or forthcoming in leading outlets, including *Political Analysis*, the *British Journal of Political Science*, *World Development*, and the *Journal of Experimental Political Science*.

<!-- RESEARCH -->
My research agenda focuses on `r research`. I focus primarily on the unintended consequences of investigating elected officials' performance and disseminating the resulting information to the general public. Scholars, governments, and civil society organizations have focused on promoting transparency in this manner to overcome the challenges to democracy around the world. However, these efforts are often not as effective as the literature would suggest due to strategic and behavioral barriers to representation.

My latest research program in this area delves into the unintended *gendered* consequences arising from increased attention to politicians' performance in office. For example, in a manuscript published at the *British Journal of Political Science*, my coauthors and I use an information experiment in Argentina to study gendered differential reactions to policy implementation. Previous work suggests that women face higher scrutiny for their performance in office. However, in the context of the implementation of a food distribution program, we find that voters are only responsive to performance information among men officeholders and tend to ignore performance information when told that an officeholder is a woman. We attribute this result to voters' perception of men politicians as the default category, and the tendency to believe that women politicians' good performance stems from factors beyond the incumbent's control. This finding calls attention to an unforeseen informational imbalance on survey experimental work in the subject, which future studies should take into account.

As another example, in a collaborative piece published in *World Development*, we discuss how the COVID-19 pandemic, through increased discontent with the performance of male-led executives and by priming a health issue commonly associated with women, lead to an increased demand for female political representation. However, as we show in a separate book chapter in *Norms, Gender and Corruption: Understanding the Nexus*, this increased demand for representation, even if met by an increased supply of women seeking elected office, does not immediately translate into descriptive representation due to a combination of social and institutional barriers that prevent women challengers from competing in equal footing.

This program is evolving in two directions. First, the attention to the study of unintended consequences has led to produce scholarship on improving research design in a way that facilitates the detection of hard-to-observe social and political phenomena. For example, a piece published in *Political Analysis*, we discuss how implementing alternatives to the standard experimental design, such as block randomization or repeated measures, may attenuate expected precision gains via explicit or implicit sample loss, a concern that prevents researchers from applying these techniques widely. Through three replications and six reanalyses of previously published experiments in leading political science journals, we show how precision gains from alternative designs can withstand significant degrees of sample loss.

As another example, in a solo-authored publication in the *Journal of Experimental Political Science*, I discuss the unforeseen costs of implementing double list experiments. This is a variant of the list experiment that promises narrower confidence intervals but comes with under-explored questionnaire design complications in the form of carryover design effects, a special kind of question order effect. I introduce statistical tests to diagnose this effect, which in turn facilitate the implementation of a more efficient technique.

Second, this program is expanding toward the study of organized crime in unexpected contexts as another hard-to-observe phenomena that challenges democratic governance. In a project recently award
an *European Research Council Starting Grant*, we seek to understand criminal governance in least-expected contexts from a comparative perspective. Focusing on the use of criminal governance tools in Argentina, Chile, Costa Rica, and Uruguay, we seek to expand the discipline's understanding of how criminal organizations shape and control life in the communities they operate.

<!-- TEACHING -->
<!-- Remember to tweak based on whether the job is cp friendly -->
At Northwestern, I primarily teach courses on quantitative methods. I lead the first course in the PhD methods sequence, focusing on probability and statistical inference, the required undergraduate level introduction to empirical political science, and a seminar on evidence-informed decision-making. I also lead the math camp for incoming political science and sociology students and run a year-long statistical computing workshop that introduces cutting-edge statistical programming practices. Later this year, I will also offer a PhD seminar on machine learning.

Before joining Northwestern, I taught data analysis for public policy and public opinion at McMaster. At Tulane, I taught an introductory course on comparative politics and and an elective on evidence-based policy to address social and political challenges in developing democracies. Beyond the classroom, I am currently mentoring a rising sophomore as part of the Farrell Fellowship program at Northwestern, with the objective of incorporating them as a co-author on projects on experimental research design.

<!-- Take this out to fit pages -->
<!-- These experiences have prepared me to teach to a diverse student body, to adapt to both online and in-person platforms, and to teach both the theory and application of quantitative methods. -->

<!-- Teaching plans -->
<!-- Remember to switch from teaching portfolio/website accordingly -->
<!-- Also tweak depending on job -->
I am prepared to teach courses on `r courses`. You can find copies of current and future syllabi in my `r source`.



<!-- CLOSING -->
I believe my expertise makes me an excellent fit at `r place`. If you have any questions, you can contact me via email or phone.


Sincerely,



