---
title: "Gustavo Diaz CV"
author:
  firstname: Gustavo
  lastname: Diaz
  address: "Scott Hall 103, 601 University Place, Evanston, Illinois"
  position: "Department of Political Science ・ Northwestern University"
  contacts:
    - icon: fa envelope
      text: gustavo.diaz@northwestern.edu
      url: "mailto:gustavo.diaz@northwestern.edu"
    - icon: fa brands github
      text: gustavo-diaz
      url: https://github.com/gustavo-diaz
    - icon: assets/icon/bsky.svg
      text: gustavodiaz.org
      url: https://twitter.com/gusvalo
    - icon: assets/icon/bi-house-fill.svg
      text: gustavodiaz.org
      url: https://gustavodiaz.org/
format: awesomecv-typst
style:
   color-accent: "000000"
---
```{=typst}
#set text(
  size: 10pt
)

#show link: set text(blue)
```


# Positions

```{=typst}
#resume-entry(
  title: "Northwestern University",
  description: "Assistant Professor of Instruction, Department of Political Science",
  date: "2024 -"
)

#resume-entry(
  title: "McMaster University",
  description: "Postdoctoral Fellow, Department of Political Science",
  date: "2022 - 2024"
)

#resume-entry(
  title: "Tulane University",
  description: "Postdoctoral Fellow, Center for Inter-American Policy and Research",
  date: "2021 - 2022"
)
```

# Education

```{=typst}
#resume-entry(
  title: "University of Illinois Urbana-Champaign",
  description: "PhD in Political Science
MA in Political Science",
  date: "2021
2017",
)

#resume-entry(
  title: "Pontificia Universidad Católica de Chile",
  description: "BA in Political Science",
  date: "2014"
)
```

# Publications  

```{=typst}
#set enum(
  reversed: true
)
```

1. **Diaz, Gustavo** and Erin Rossiter. 2025. ["Balancing Precision and Retention in Experimental Design."](https://doi.org/10.1017/pan.2025.10008) *Political Analysis*

1. **Diaz, Gustavo**, Virginia Oliveros, Rebecca Weitz-Shapiro, and Matthew S. Winters. 2025. ["Ignoring Female Performance: A Survey Experiment on Policy Implementation in Argentina."](https://doi.org/10.1017/S0007123424000668) *British Journal of Political Science* 55: e54  

1. **Diaz, Gustavo**. 2024. ["Assessing the Validity of Prevalence Estimates in Double List Experiments."](https://doi.org/10.1017/XPS.2023.24) *Journal of Experimental Political Science* 11(2): 162-174

1. Piazza, Kelly Senters and **Gustavo Diaz**. 2024. ["Data Sources for the Study of Gender and Corruption."](https://gustavodiaz.org/files/research/data_corruption.pdf) In *Handbook on Gender and Corruption in Democracies*, edited by Emily Beaulieu Bacchus and Tiffany Barnes. Edward Elgar Publishing

1. **Diaz, Gustavo** and Kelly Senters Piazza. 2022. ["Women Held Back: The Depressing Effect of Institutional and Norms-Based Barriers on Female Representation in Corrupt Contexts."](https://gustavodiaz.org/files/research/gender_corruption.pdf) In [*Norms, Gender and Corruption: Understanding the Nexus*](https://www.e-elgar.com/shop/gbp/norms-gender-and-corruption-9781802205824.html), edited by Ina Kubbe and Ortrun Merkle. Edward Elgar Publishing

1. Piazza, Kelly Senters and **Gustavo Diaz**. 2020. ["Light in the Midst of Chaos: COVID-19 and Female Political Representation."](https://doi.org/10.1016/j.worlddev.2020.105125) *World Development* 136: 105125 (with Kelly Senters Piazza)

1. **Diaz, Gustavo**, Christopher Grady, and James H. Kuklinski. 2020. ["Survey Experiments and the Quest for Valid Interpretation."](https://gustavodiaz.org/files/research/sage_survey_experiments_chapter.pdf) In [*The SAGE Handbook of Research Methods in Political Science and International Relations*](https://us.sagepub.com/en-us/nam/the-sage-handbook-of-research-methods-in-political-science-and-international-relations/book262875), edited by Luigi Curini and Robert Franzese. London: Sage

1. **Diaz, Gustavo**. 2014. ["Civic Education and Voter Turnout Under Voluntary Voting."](https://revistapolitica.uchile.cl/index.php/RP/article/view/33099/34813) *Política* 52(1): 61-91 (In Spanish)

```{=typst}
#set enum(
  reversed: false
)
```

# Selected Working Papers

[Two-Sided Sensitivity Bias in List Experiments: Support for Same-Sex Marriage in Argentina""](https://gustavodiaz.org/files/research/ssm_arg.pdf) (with Jordi Díez and Michelle Dion) *Under review*

["Combining List Experiments and the Network Scale-Up Method to Improve Prevalence Estimates of Sensitive Attitudes and Behaviors."](https://gustavodiaz.org/files/research/list_nsum.pdf) (with Ines Fynn, Verónica Pérez Bentancur, and Lucía Tiscornia)

["In the Crevices of the State: Criminal Governance in Unexpected Contexts."](https://gustavodiaz.org/files/research/crevices.pdf) (with Ines Fynn, Verónica Pérez Bentancur, and Lucía Tiscornia)

# Teaching  

**Northwestern University** 

[Introduction to Empirical Methods in Political Science](https://gustavodiaz.org/ps210/syllabus.pdf)  `#h(1fr)`{=typst} Spring & Winter 2026, 2025

Machine Learning (Graduate) `#h(1fr)`{=typst} Winter 2026

[Probability and Statistics (Graduate)](https://gustavodiaz.org/files/teaching/prob_stats.pdf) `#h(1fr)`{=typst} Fall 2025, 2024

[Math Camp (Graduate)](https://gustavodiaz.org/NUmathcamp) `#h(1fr)`{=typst} Summer 2025

[Statistical Computing Workshop](https://gustavodiaz.org/rworkshop/) `#h(1fr)`{=typst} AY 2025-26, 2024-25

[Evidence-Informed Decision-Making](https://gustavodiaz.org/ps395e/syllabus.pdf) `#h(1fr)`{=typst} Spring 2025

**McMaster University**  

[Research Design for Public Opinion and Public Policy](https://popw24.gustavodiaz.org/) `#h(1fr)`{=typst} Spring 2023-24

**Tulane University**  

[Politics of Developing Democracies](https://gustavodiaz.org/files/teaching/ddem_syllabus.pdf) `#h(1fr)`{=typst} Spring 2022

[Comparative Politics](https://gustavodiaz.org/teaching/cp_intro/syllabus/polc2300_syllabus.pdf)  `#h(1fr)`{=typst} Fall 2021

# Awards

2019-2020\. Werner Baer Dissertation Writing Fellowship. Lemann Center for Brazilian Studies,
University of Illinois

2019\. Best Poster Award. Latin American Political Methodology Meeting. Montevideo, Uruguay

2016\. Rita and Leonard Ogren Award for Academic Excellence. Department of Political Science,
University of Illinois

# Invited Talks and Conference Presentations

2025: Texas Methods Meeting. University of Houston \
`#h(1cm)`{=typst} Computation and Data Exchange. Northwestern University \
`#h(1cm)`{=typst} Midwest Political Science Association. Chicago, IL

2024: International Society of Political Psychology. Santiago, Chile \
`#h(1cm)`{=typst} MapleMeth. Western University, Canada \
`#h(1cm)`{=typst} Midwest Political Science Association. Chicago, IL

2023: MapleMeth. Western University, Canada \
`#h(1cm)`{=typst} American Political Science Association. Los Angeles, CA \
`#h(1cm)`{=typst} Annual Meeting of the Society for Political Methodology. Stanford University

2022: Spark Centre for Social Research Innovation. McMaster University, Canada \
`#h(1cm)`{=typst} Midwest Political Science Association. Chicago, IL \
`#h(1cm)`{=typst} American Political Science Association. Montréal, QC, Canada \
`#h(1cm)`{=typst} Annual Meeting of the Society for Political Methodology. Washington University in St. Louis \
`#h(1cm)`{=typst} Political Economy of Development Virtual Workshop. Journal of Public Policy \
`#h(1cm)`{=typst} Souther Political Science Association. San Antonio, TX \
`#h(1cm)`{=typst} Latin American Political Methodology Meeting. Universidad de San Andrés, Argentina

2021: Methods Reading Group. American University \
`#h(1cm)`{=typst} Graduate Student Exchange, Washington University in St. Louis \
`#h(1cm)`{=typst} Midwest Political Science Association. Chicago, IL \
`#h(1cm)`{=typst} American Political Science Association. Seattle, WA \
`#h(1cm)`{=typst} Annual Meeting of the Society for Political Methodology. New York University \
`#h(1cm)`{=typst} Latin American Political Methodology Meeting. ITAM, Mexico \
`#h(1cm)`{=typst} Quantitative Political Economy Research Group. King's College London \
`#h(1cm)`{=typst} Midwest Workshop in Empirical Political Science. Purdue University \
`#h(1cm)`{=typst} NYU-CESS Annual Experimental Political Science Conference. New York University

2020: Graduate Student Exchange. University of Notre Dame \
`#h(1cm)`{=typst} Latin American Political Methodology Meeting. Universidade de São Paulo, Brazil \
`#h(1cm)`{=typst} NYU-CESS Annual Experimental Political Science Conference. New York University 

2019: American Political Science Association. Washington, DC \
`#h(1cm)`{=typst} Latin American Political Methodology Meeting. Universidad Católica del Uruguay \
`#h(1cm)`{=typst} Political Methodology Colloquium. University of Minnesota \
`#h(1cm)`{=typst} St. Louis Area Methods Meeting. Southern Illinois University 


# Additional Training  

2023\. Grant writing workshop for junior faculty. McMaster University

2019\. Empirical Implications of Theoretical Models Summer Institute. Emory University

2014\. Summer School on Mixed Methods. Pontificia Universidad Católica de Chile

# Skills  

**Languages:** Spanish, French, Portuguese

**Software:** R, STATA, GIS, GitHub, LaTeX, Markdown, Typst, Quarto