---
format: pdf
fontsize: 12pt
urlcolor: blue
---
## Teaching Evaluations

Gustavo Diaz  
*Department of Political Science*  
*Northwestern University*  
<gustavo.diaz@northwestern.edu>  
\hrule

&nbsp;

The following tables present a summary of my teaching evaluations. Unless otherwise noted, scores range from 1 to 5, with 5 being the most positive. Detailed evaluations available upon request.

# McMaster University

In Spring 2024, only 2 students completed the evaluations for my data analysis for public opinion and policy course, while in Spring 2023 only 1 student did. While the average course rating among these responses is 9 on a scale from 1 (very poor) to 10 (excellent), they stem from response rates of 18% and 5%, respectively, which is too low to provide a reliable summary of student evaluations.

# Tulane University

\begin{table}[h!]
	\begin{center}
	\footnotesize
	\begin{tabular}{lccccccc}
	\hline 
	\hline 
	&	Class	&	Evaluations & Feedback & Knowledge & Recommend & Instructor & N	\\
	\hline
	Developing Democracies & 4.6 & 4.4 & 4.6 & 4.0 & 4.6 & 5 \\
	(Spring 2022) &		&		&		& & & &\\
	Comparative Politics & 4.2	& 4.7	& 4.1	 & 4.5  & 4.1 & 4.5 & 14\\
	(Fall 2021)&		&		&		& & & &\\
	\hline
  \end{tabular}
	\end{center}
\end{table}

## Selected comments from students at Tulane

- "Professor Diaz is very understanding and does a great job applying concepts to class discussions and the out-of-class assignments reflect the key concepts of the course."

- "I appreciated the flexible exam structure and edits made to the syllabus as a result of the challenges of this semester. I enjoyed the News Report assignments as they were an interesting way to interact with the course content in a meaningful way."

- "The organization of content felt extremely coherent as we built on every previous module. This is no small feat given the subject matter. The mixture of quizzes and News Report assignments kept the course from being stale while still testing our knowledge of course material from differing vectors."


# University of Illinois at Urbana-Champaign

\begin{table}[h!]
	\begin{center}
	\scriptsize
	\begin{tabular}{lcccccccc}
	\hline 
	\hline 
	&	Course quality	&	Teaching & Sensitivity & Respectful & Motivation & Preparation & Accessible & N	\\
	\hline
	Developing Countries & 4.1	& 4.2	& - &- & -&- &- & 17	\\
	(Summer 2019 Online)&		&	&	& & & & &	\\
		Data Analysis & 3.9	& 4.0 & 4.8	& 5.0 & 4.4 & 4.7 & 4.7 & 16 \\
	(Fall 2017 TA)&		&		&		\\
	Developing Countries & 4.1	& 3.8	& 4.4	 & 4.9  & 3.7 & 4.5 & 4.5 & 39 \\
	(Fall 2016 TA)&		&		&		& & & & & \\
	\hline									
	\hline
	\multicolumn{5}{l}{\textit{Note: Online courses at UIUC only evaluate the course as a whole.}}\\					
	\end{tabular}
	\end{center}
\end{table}

